### ISSUE TITLE
Keybinds I've made won't trigger (1.11.2)

### ISSUE THREAD

**Issue by Murrlin** [The-Fireplace-Minecraft-Mods/Command-Keybindings#2]
...but the commands themselves work fine.
(do I need to mention forge version, what keys I'm trying to use, etc?)

**Comment by The-Fireplace** [comment]
It couldn't hurt to mention Forge version, Mod version, etc. Also, if you
could provide your fml-client-latest.log.

**Comment by Murrlin** [comment]
forge 13.20.0.2294, mod v. 7.01,
*rerunning MC to refresh the log* OMG WHY DOES IT WORK NOW *sigh*
I'm so sorry for taking up your time! But thank you for your quick replies!
Please close.  (I'm so embarrassed)
